### PR TITLE
pool_name related changes in run_sync_test  in uzfs_test_sync.sh

### PR DESCRIPTION
**Pull request by mynktl**
##### Changes in pool_name in uzfs_test_sync.sh
       - To avoid conflict between tests.
##### Changing build config to USER for ZFS in travis userspace build
       - This change will help in reducing travis build time for userspace build
##### Avoid running ZTEST in parallel with ZVOL related test by uzfs_test
       - ZTEST and uzfs_test are using vdev-files from /tmp directory. Running ZTEST 
          and uzfs_test in parallel leads to two issues : 
                1. Panic in ZTEST. Since we are running ZTEST and uzfs_test
                    in parallel, MMP writes in ZTEST will have much delay which
                    will lead to panic as spa mode in ZTEST is set to PANIC.

                 2. ZTEST have a test case to replace disk-file in RAIDZ pool.
                    In uzfs_zvol_test we are importing pool through CLI by
                    scanning files in /tmp directory. At some point, when replace
                    is in-progress in ZTEST and While doing import through
                    ZPOOL we get an assertion failure in spa_config_valid for
                    ztest pool as ondisk config (at vdev level) and zpool.cache
                    will be different.

### CODE REVIEW

**Review by vishnuitta — COMMENTED** [review]
run_zrepl_uzfs_test and run_zrepl_rebuild_uzfs_test need to do export. They are using same pool, and, I think they are not running in parallel, and so, using same pool should be fine.

**Review by jkryl — APPROVED** [review]

**Comment by mynktl** [comment]
@vishnuitta 
In run_zrepl_uzfs_test and run_zrepl_rebuild_uzfs_test, we are sending IO's over network from uzfs_test to zrepl. So i haven't exported pool in both the test cases.

**Comment by vishnuitta** [comment]
you are right @mynktl ..
In run_uzfs_test, pool6 has been used twice.. it should be OK as we are doing cleanup.. may be worth to change its name..
as part of cleanup, can you add 'zpool label clear' and writing 0's to disk for initial 100MB of disk
And, for which pool name, we got the seg fault in travis?

**Comment by mynktl** [comment]
@vishnuitta 
Thanks for pointing out same pool_name in run_uzfs_test. I will change pool_name for that test.
As part of cleanup, we are destroying disk itself in cleanup_uzfs_test. So, zpool label clear may not be needed in this case.
In travis, script exited with assertion error logs only, we couldn't figure out pool_name for which assertion triggered.

**Comment by vishnuitta** [comment]
Mayank, its still better to do 'zpool label clear' and zeriong out of 100MB during cleanup time.. we won't be sure how ext4 is providing this truncated file, i.e., whether its creating at altogether new place or giving the same place on disk without zeriong it. Also, lets print the pool name in our scripts, so that, we can find the pool name for which issue is coming .

**Comment by mynktl** [comment]
Ok.

**Review by vishnuitta — COMMENTED** [review]
These changes are good. But, I don't see the changes of the import API call in uzfs_test framework which sets import_args.

**Comment by mynktl** [comment]
@vishnuitta  @jkryl  I have updated PR. Please re-review changes.

**Comment by vishnuitta** [comment]
Changes are good

**Pull request merged**
